default["s3"]["_ACCESS_KEY"] = ""
default["s3"]["_SECRET_KEY"] = ""
default["s3"]["_S3_BUCKETS_NAME"] = ""
default["backup"]["_BACKUP_DIRECTORY"] = "/var, /tmp"
default["backup"]["_BACKUPED_FILE_PREFIX"] = "filebackup"
default["backup"]["_BACKUPED_DB_PREFIX"] = "dbbackup"
